#!/bin/sh
# Adds a section for a new release to the top of CHANGELOG.md, with notes
# generated by GitHub from the pull requests merged since the last release
# tag. Edit the notes, then commit the file in the release pull request.
# The first line of CHANGELOG.md is where the build reads the version, see
# docs/versioning-and-releases.md.
#
# Usage: ./changelog-generator.sh vX.Y.Z [branch]
#
# The notes cover the pull requests merged into the branch (default main,
# which must exist on GitHub) since the last release tag.
set -eu

tag=${1:?usage: $0 vX.Y.Z [branch]}
branch=${2:-main}
case "$tag" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "The version must look like v4.2.0" >&2; exit 1 ;;
esac

cd "$(dirname "$0")"

if head -1 CHANGELOG.md | grep -q "^# $tag "; then
  echo "CHANGELOG.md already starts with $tag" >&2
  exit 1
fi

# Check if github cli tool gh is installed and show where to install it if not
command -v gh >/dev/null 2>&1 || { echo "Please install the GitHub CLI tool from https://cli.github.com/" >&2; exit 1; }
repo=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
if ! notes=$(gh api "repos/$repo/releases/generate-notes" \
  -f tag_name="$tag" -f target_commitish="$branch" --jq .body); then
  echo "Could not generate the notes for $tag on $branch" >&2
  exit 1
fi
notes=$(printf '%s' "$notes" | tr -d '\r')

{
  echo "# $tag - $(date +%Y-%m-%d)"
  echo
  printf '%s\n' "$notes"
  echo
  cat CHANGELOG.md
} > CHANGELOG.md.new
mv CHANGELOG.md.new CHANGELOG.md

echo "Added $tag to the top of CHANGELOG.md. Edit the notes, then commit it."
