// This file is auto-generated by @hey-api/openapi-ts

export const $Location = {
    maxItems: 2,
    minItems: 2,
    type: 'array',
    items: {
        type: 'number',
        format: 'float32'
    }
} as const;

export const $DatasetId = {
    type: 'string'
} as const;

export const $DatasetItemId = {
    type: 'string'
} as const;

export const $DatasetItem = {
    type: 'object'
} as const;

export const $Dataset = {
    type: 'array',
    items: {
        '$ref': '#/components/schemas/Location'
    }
} as const;