// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { DatasetData, DatasetError, DatasetResponse, DatasetSearchData, DatasetSearchError, DatasetSearchResponse, DatasetItemData, DatasetItemError, DatasetItemResponse } from './types.gen';

export const client = createClient(createConfig({baseUrl: import.meta.env.VITE_API_URL}));

/**
 * obtains a dataset
 * Obtains a dataset by its ID, which by passing in the appropriate options, might be in different formats
 *
 */
export const dataset = <ThrowOnError extends boolean = false>(options: Options<DatasetData, ThrowOnError>) => { return (options?.client ?? client).get<DatasetResponse, DatasetError, ThrowOnError>({
    ...options,
    url: '/dataset/{datasetId}'
}); };

/**
 * obtains a list of dataset entries satisfying the search criteria supplied
 * Obtains a dataset by its ID, which by passing in the appropriate options, might be in different formats
 *
 */
export const datasetSearch = <ThrowOnError extends boolean = false>(options: Options<DatasetSearchData, ThrowOnError>) => { return (options?.client ?? client).get<DatasetSearchResponse, DatasetSearchError, ThrowOnError>({
    ...options,
    url: '/dataset/{datasetId}/search'
}); };

/**
 * obtains a dataset item by its  unique ID
 * Obtains a dataset item by its ID, and the dataset's ID.
 *
 */
export const datasetItem = <ThrowOnError extends boolean = false>(options: Options<DatasetItemData, ThrowOnError>) => { return (options?.client ?? client).get<DatasetItemResponse, DatasetItemError, ThrowOnError>({
    ...options,
    url: '/dataset/{datasetId}/item/{datasetItemId}'
}); };
