// This file is auto-generated by @hey-api/openapi-ts

export type Location = [
    number,
    number
];

export type DatasetId = string;

export type DatasetItemId = string;

export type DatasetItem = {
    [key: string]: unknown;
};

export type Dataset = Array<Location>;

export type DatasetData = {
    path: {
        /**
         * uniquely specifies the dataset wanted
         */
        datasetId: DatasetId;
    };
};

export type DatasetResponse = (Dataset);

export type DatasetError = (unknown);

export type DatasetSearchData = {
    path: {
        /**
         * uniquely specifies the dataset wanted
         */
        datasetId: DatasetId;
    };
    query?: {
        /**
         * uniquely specifies the taxonomy filter items wanted
         */
        filter?: Array<(string)>;
        /**
         * a text fragment to match
         */
        text?: string;
    };
};

export type DatasetSearchResponse = (Array<DatasetItemId>);

export type DatasetSearchError = (unknown);

export type DatasetItemData = {
    path: {
        /**
         * uniquely specifies the dataset wanted
         */
        datasetId: DatasetId;
        /**
         * uniquely specifies the dataset item wanted
         */
        datasetItemId: DatasetItemId;
    };
};

export type DatasetItemResponse = (DatasetItem);

export type DatasetItemError = (unknown);