// @ts-nocheck
// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "fastify-openapi-glue";
import * as dotenv from "dotenv";
import { Security } from "./security.js";
import { Service } from "./service.js";
import specification from "@mykomap/common";

dotenv.config();

const serviceOptions = {
  dataRoot: process.env.SERVER_DATA_ROOT ?? "data",
};

export default async function (fastify, opts) {
  const pluginOptions = {
    specification,
    serviceHandlers: new Service({
      options: opts.serviceOptions,
    }),
    securityHandlers: new Security(),
  };
  // Ignore the path prefix if one is set, as it is handled upstream.
  // If we do it here it gets doubled up!
  const prefix = undefined;
  fastify.register(openapiGlue, { ...pluginOptions, ...opts, prefix });
}

export const options = {
  serviceOptions,
  ajv: {
    customOptions: {
      strict: false,
    },
  },
};
