// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "fastify-openapi-glue";
import { Security } from "./security.js";
import { Service } from "./service.js";
const localFile = (fileName) => new URL(fileName, import.meta.url).pathname;

const serviceOptions = {
  dataRoot: process.env.SERVER_DATA_ROOT ?? 'data',
};


export default async function (fastify, opts) {
  const pluginOptions = {
    specification: localFile("../api/mykomap-openapi.json"),
    serviceHandlers: new Service({
      options: opts.serviceOptions,
    }),
    securityHandlers: new Security(),
  };
  fastify.register(openapiGlue, { ...pluginOptions, ...opts });
}

export const options = {
  serviceOptions,
  ajv: {
    customOptions: {
      strict: false,
    },
  },
};
