const mockItem = {
  id: "test/cuk/R000002",
  name: "Brighton Community Housing Cooperative",
  description:
    "Brighton Community Housing Cooperative is a member-owned housing cooperative dedicated to providing affordable, sustainable housing solutions in the Brighton area. Founded in 1995, we manage over 200 properties across the city, offering secure tenancies and community-focused living spaces.",
  website: ["https://www.brightonhousing.coop"],
  dc_domains: [
    "brightonhousing.coop",
    "bchc.coop",
    "brightoncoop.coop",
    "communityhousing.coop",
    "sustainablehomes.coop",
    "ecoapartments.coop",
    "victorianrenovations.coop",
    "brightoncommunity.coop",
    "affordablehousing.coop",
    "localhomes.coop",
    "communityliving.coop",
    "sustainableliving.coop",
    "brightonproperties.coop",
    "cooperativehomes.coop",
    "memberowned.coop",
    "democratichousing.coop",
    "communityfocused.coop",
    "localhousing.coop",
    "sustainablecommunity.coop",
    "brightonhomes.coop",
  ],
  country_id: "GB",
  primary_activity: "ICA210",
  organisational_structure: "OS90",
  typology: "BMT30",
  latitude: 50.850452,
  longitude: -0.924728,
  geocontainer_lat: 50.85045216,
  geocontainer_lon: -0.92472819,
  address: "123 Western Road, Brighton, East Sussex, BN1 2AB, United Kingdom",
  data_sources: ["ICA", "DC"],
};

export default mockItem;
