import React from "react";
import { Select, InputLabel, Box, MenuItem } from "@mui/material";
import type { SelectChangeEvent } from "@mui/material";

interface OptionProps {
  value: string;
  label: string;
}

interface SelectBoxProps {
  label: string;
  value: string;
  onChange: (event: SelectChangeEvent<string>, child: React.ReactNode) => void;
  id?: string;
  options?: OptionProps[];
}

const SelectBox = ({
  label,
  id,
  value,
  options,
  onChange,
  ...props
}: SelectBoxProps) => {
  const useId = () => {
    return Math.random().toString(16).slice(2);
  };

  const autoGeneratedId = useId();
  const selectId = id || autoGeneratedId;

  return (
    <Box>
      <InputLabel htmlFor={selectId}>
        {label}
      </InputLabel>
      <Select
        id={selectId}
        value={value}
        onChange={onChange}
        aria-labelledby={selectId}
        role="listbox"
        {...props}
      >
        {options?.map((option) => (
          <MenuItem key={option.value} value={option.value} role="option">
            {option.label}
          </MenuItem>
        ))}
      </Select>
    </Box>
  );
};

export default SelectBox;
